# Practical 01: Dataset Ingestion, Inspection & Descriptive Statistics with Pandas

**UNIT 1: Introduction to Big Data and Large Dataset Handling**

**Problem Statement:** Write a Python program using Pandas to load a structured dataset (CSV/JSON), display its first 5 rows, last 5 rows, dimensions (shape), column names, and data types with info(). Generate comprehensive summary statistics of all numeric and categorical attributes using describe(include='all').

In [1]:
import io
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None, "display.width", 200)

rs = np.random.default_rng(11)
n = 250
base = pd.DataFrame({
    "Order ID": np.arange(1001, 1001 + n),
    "Customer Name": [f"Cust-{i:03d}" for i in rs.integers(1, 80, n)],
    "City": rs.choice(["Kochi", "Chennai", "Mumbai", "Bengaluru", "Hyderabad", "Pune"], n),
    "Product Category": rs.choice(["Electronics", "Furniture", "Groceries", "Sports", "Books"], n),
    "Quantity": rs.integers(1, 8, n),
    "Unit Price": np.round(rs.uniform(200, 6000, n), 2),
    "Discount %": rs.choice([0, 10, 15, 20, 30], n),
    "Order Date": pd.date_range("2025-06-01", periods=n, freq="D").strftime("%Y-%m-%d"),
})

csv_buf = io.StringIO()
base.to_csv(csv_buf, index=False)
csv_buf.seek(0)
json_buf = io.StringIO(base.to_json(orient="records"))

data = pd.read_csv(csv_buf)
print("Dataset loaded successfully!")

print(data.head())

print(data.tail())

print("Shape (rows, columns):", data.shape)
print("Column names:", data.columns.tolist())

data.info()

print(data.describe(include='all'))

df_from_json = pd.read_json(json_buf)
print("JSON load – shape:", df_from_json.shape)
print(df_from_json.head())

Dataset loaded successfully!

   Order ID  Customer Name       City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001       Cust-011     Mumbai       Electronics         7     1639.04          30  2025-06-01
1      1002       Cust-011  Bengaluru         Furniture         3     2966.74           0  2025-06-02
2      1003       Cust-063      Kochi         Groceries         5      464.43           0  2025-06-03
3      1004       Cust-040     Mumbai             Books         1     1869.70          15  2025-06-04
4      1005       Cust-047      Kochi         Furniture         6     5889.61          10  2025-06-05

     Order ID  Customer Name    City  Product Category  Quantity  Unit Price  Discount %  Order Date
245      1246       Cust-044  Mumbai         Furniture         4     3564.97          20  2026-02-01
246      1247       Cust-020    Pune         Furniture         5     3625.13          30  2026-02-02
247      1248       Cust-051    Pune         Groceries         5     4967.65          30  2026-02-03
248      1249       Cust-013   Kochi       Electronics         5      751.80           0  2026-02-04
249      1250       Cust-026    Pune         Furniture         6     2455.63          10  2026-02-05

Shape (rows, columns): (250, 8)
Column names: ['Order ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Price', 'Discount %', 'Order Date']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          250 non-null    int64
 1   Customer Name     250 non-null    object
 2   City              250 non-null    object
 3   Product Category  250 non-null    object
 4   Quantity          250 non-null    int64
 5   Unit Price        250 non-null    float64
 6   Discount %        250 non-null    int64
 7   Order Date        250 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 15.8+ KB

           Order ID  Customer Name       City  Product Category    Quantity   Unit Price  Discount %  Order Date
 count   250.000000            250        250               250  250.000000   250.000000  250.000000         250
unique          NaN             74          6                 5         NaN          NaN         NaN         250
   top          NaN       Cust-012  Hyderabad         Furniture         NaN          NaN         NaN  2025-06-01
  freq          NaN              8         53                58         NaN          NaN         NaN           1
  mean  1125.500000            NaN        NaN               NaN    4.080000  3050.207880   14.640000         NaN
   std    72.312977            NaN        NaN               NaN    1.955735  1683.457318    9.339126         NaN
   min  1001.000000            NaN        NaN               NaN    1.000000   240.290000    0.000000         NaN
   25%  1063.250000            NaN        NaN               NaN    2.000000  1624.972500   10.000000         NaN
   50%  1125.500000            NaN        NaN               NaN    4.000000  2987.845000   15.000000         NaN
   75%  1187.750000            NaN        NaN               NaN    6.000000  4521.367500   20.000000         NaN
   max  1250.000000            NaN        NaN               NaN    7.000000  5938.880000   30.000000         NaN

JSON load – shape: (250, 8)

   Order ID  Customer Name       City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001       Cust-011     Mumbai       Electronics         7     1639.04          30  2025-06-01
1      1002       Cust-011  Bengaluru         Furniture         3     2966.74           0  2025-06-02
2      1003       Cust-063      Kochi         Groceries         5      464.43           0  2025-06-03
3      1004       Cust-040     Mumbai             Books         1     1869.70          15  2025-06-04
4      1005       Cust-047      Kochi         Furniture         6     5889.61          10  2025-06-05